apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-caas
  annotations:
    meta.crossplane.io/maintainer: The configuration-caas Configuration
    meta.crossplane.io/source: github.com/upbound/configuration-caas
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration-caas configuration offers Kubernetes Clusters.
    meta.crossplane.io/readme: |
      This Configuration bundles an Upbound Cloud extension and an API
      definition. The API will allow control planes to provision fully
      configured Kubernetes Service clusters, composed
      using cloud service primitives from the Upbound Official Providers
spec:
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.15.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.9.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v0.38.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: ">=v0.38.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v0.38.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.1.3"
